Homer_MVC/Models/ProyectosViewModels.cs
using System.Collections.Generic;

namespace Homer_MVC.Models
{
    public class proyecto
    {
        public bool HasPassword { get; set; }
        //public IList<UserLoginInfo> Logins { get; set; }
        public string PhoneNumber { get; set; }
        public bool TwoFactor { get; set; }
        public bool BrowserRemembered { get; set; }
    }
}

Homer_MVC/Controllers/ProyectoController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homer_MVC.Controllers
{
    public class ProyectoController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult DetallesProyecto(string nombreProyecto)
        {
            ViewBag.nombreProyecto = nombreProyecto;
            return View();
        }
    }
}

Homer_MVC/Controllers/TablesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Homer_MVC.Controllers
{
    public class TablesController : Controller
    {
        
        public ActionResult TablesDesign()
        {
            return View();
        }

        public ActionResult DataTables()
        {
            return View();
        }

        public ActionResult FooTable()
        {
            return View();
        }

        public JsonResult tableJsonData()
        {

            // Creat basic JSON object with data for table
            var tableData = new[] 
            {
                new [] { "Tiger Nixon", "System Architect", "Edinburgh", "61", "2011/04/25", "$320,800" },
                new [] { "Garrett Winters", "Accountant", "Tokyo", "63", "2011/07/25", "$170,750" },
                new [] { "Ashton Cox", "Junior Technical Author", "San Francisco", "66", "2009/01/12", "$86,000" },
                new [] { "Cedric Kelly", "Senior Javascript Developer", "Edinburgh", "22", "2012/03/29", "$433,060" },
                new [] { "Airi Satou", "Accountant", "Tokyo", "33", "2008/11/28", "$162,700" },
                new [] { "Brielle Williamson", "Integration Specialist", "New York", "61", "2012/12/02", "$372,000" },
                new [] { "Herrod Chandler", "Sales Assistant", "San Francisco", "59", "2012/08/06", "$137,500" },
                new [] { "Rhona Davidson", "Integration Specialist", "Tokyo", "55", "2010/10/14", "$327,900" },
                new [] { "Colleen Hurst", "Javascript Developer", "San Francisco", "39", "2009/09/15", "$205,500" },
                new [] { "Sonya Frost", "Software Engineer", "Edinburgh", "23", "2008/12/13", "$103,600" },
                new [] { "Jena Gaines", "Office Manager", "London", "30", "2008/12/19", "$90,560" },
                new [] { "Quinn Flynn", "Support Lead", "Edinburgh", "22", "2013/03/03", "$342,000" }
            };

            var dataTable = 
                new {data = tableData} 
            ;

            // Return JSON object
            return Json(dataTable, JsonRequestBehavior.AllowGet);

        }

    }
}

Homer_MVC/Views/Proyecto/VistaGridGlobal.cshtml
@{
    ViewBag.Title = "Proyectos";
}

<div class="p-lg">
    <div class="row">
        <div class="center-block panel-info tooltip-demo">
            <button onclick="@Url.Action("DetallesProyecto", "Proyecto")" type="button" style="float:right;" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="Vista en Tabs"><i class="fa fa-th-large fa-2x"></i></button>
            <button onclick="@Url.Action("VistaGridGlobal", "Proyecto")" type="button" style="float:right;" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="Vista en Grid"><i class="fa fa-table fa-2x"></i></button>
        </div>
    </div>     
    <div class="row">
        <div class="table-responsive">
            <div class="tooltip-demo" style="float:right;">
                <button type="button" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="Exportar a PDF"><i class="fa fa-file-pdf-o fa-2x"></i></button>
                <button type="button" class="btn btn-sm btn-default" data-toggle="tooltip" data-placement="top" title="Exportar a CSV"><i class="fa fa-file-excel-o fa-2x"></i></button>
            </div>
            <p class="font-extra-bold">Todos los parámetros monitorizados del equipo</p>
            <table id="example2" class="table table-bordered">
                <thead>
                    <tr>
                        <th>Parámetro</th>
                        <th>Descripción</th>
                        <th>Esperado</th>
                        <th>Actual</th>
                        <th>Estado</th>
                        <th>Comentarios</th>
                    </tr>
                </thead>
                <tbody>
                    <tr class="alert alert-success">
                        <td>Sincronización horaria</td>
                        <td>La hora del sistema debe estar sincronizada</td>
                        <td>&#60 500ms</td>
                        <td>302ms</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Servidor horario PPCSTA01</td>
                    </tr>
                    <tr class="alert alert-danger">
                        <td>Uso CPU</td>
                        <td>% de uso de la CPU</td>
                        <td>&#60 75%</td>
                        <td>78%</td>
                        <td align="center"><i class="fa fa-exclamation"></i></td>
                        <td>Intel Core i7 3'1GHz 4 núcleos</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>Ocupación disco</td>
                        <td>Unidad C:\</td>
                        <td>&#60 75%</td>
                        <td>67%</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Tamaño del disco: 500GB</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>Uso RAM</td>
                        <td>Porcentaje de RAM ocupada</td>
                        <td>&#60 75%</td>
                        <td>30%</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Cuenta con 8GB</td>
                    </tr>
                    <tr class="alert alert-danger">
                        <td>Estado Historical</td>
                        <td>Estado del servicio de Historicos</td>
                        <td>Hot / Standby</td>
                        <td>Fail</td>
                        <td align="center"><i class="fa fa-exclamation"></i></td>
                        <td>El servicio no se encuentra activo</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>Ocupación BD</td>
                        <td>Ocupación de las bases de datos</td>
                        <td>&#60 75%</td>
                        <td>56%</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Nombre de la Base de Datos OASYSDNA\Historical</td>
                    </tr>
                    <tr class="alert alert-danger">
                        <td>Fragmentación BD</td>
                        <td>Estado de fragmentación de la BD</td>
                        <td>&#60 40%</td>
                        <td>65%</td>
                        <td align="center"><i class="fa fa-exclamation"></i></td>
                        <td>Es necesario realizar una desfragmentación de las bases de datos</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>AA Sincronización horaria</td>
                        <td>La hora del sistema debe estar sincronizada</td>
                        <td>&#60 500ms</td>
                        <td>302ms</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Servidor horario PPCSTA01</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>AA Sincronización horaria</td>
                        <td>La hora del sistema debe estar sincronizada</td>
                        <td>&#60 500ms</td>
                        <td>302ms</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Servidor horario PPCSTA01</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>AA Sincronización horaria</td>
                        <td>La hora del sistema debe estar sincronizada</td>
                        <td>&#60 500ms</td>
                        <td>302ms</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Servidor horario PPCSTA01</td>
                    </tr>
                    <tr class="alert alert-success">
                        <td>AA Sincronización horaria</td>
                        <td>La hora del sistema debe estar sincronizada</td>
                        <td>&#60 500ms</td>
                        <td>302ms</td>
                        <td align="center"><i class="fa fa-check"></i></td>
                        <td>Servidor horario PPCSTA01</td>
                    </tr>
                </tbody>
            </table>
        </div>
    </div>
</div>

@section Styles {
    @Styles.Render("~/bundles/datatables/css")
}

@section Scripts {
    @Scripts.Render("~/bundles/datatables/js")
    @Scripts.Render("~/bundles/datatablesBootstrap/js")

    <script type="text/javascript">

        $(function () {

            // JSON data
            var chartDataUrl = '@Url.Action("tableJsonData", "Tables")';

            // Initialize Example 1
            $('#example1').dataTable({
                "ajax": chartDataUrl
            });

            // Initialize Example 2
            $('#example2').dataTable();

        });
    </script>